### ISSUE TITLE
TODO - Jack

### ISSUE THREAD

**Issue by jackgude-unl** [jackgude-unl/GroceryApp#1]
- [ ] SQL for Database
- [ ] Link Accessors and DB
- [ ] Implement Sale interface and class
- [ ] Figure out product images
- [ ] Figure out login feature
- [ ] Implement interface / class for payment info / user address?
